/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_i2c.h"
#include "fsl_spi.h"
#include "fsl_reset.h"
#include "fsl_usart.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals_cm33_core0 functional group */
/* BOARD_InitPeripherals_cm33_core0 defines for FLEXCOMM1 */
/* Definition of peripheral ID */
#define OLED_I2C_FC1_PERIPHERAL ((I2C_Type *)FLEXCOMM1)
/* Definition of the clock source frequency */
#define OLED_I2C_FC1_CLOCK_SOURCE 12000000UL
/* BOARD_InitPeripherals_cm33_core0 defines for FLEXCOMM3 */
/* Definition of peripheral ID */
#define VALVES_SPI_FC3_PERIPHERAL ((SPI_Type *)FLEXCOMM3)
/* Definition of the clock source frequency */
#define VALVES_SPI_FC3_CLOCK_SOURCE 12000000UL
/* BOARD_InitPeripherals_cm33_core0 defines for FLEXCOMM8 */
/* Definition of peripheral ID */
#define NEOPIXELS_SPI_FC8_PERIPHERAL ((SPI_Type *)FLEXCOMM8)
/* Definition of the clock source frequency */
#define NEOPIXELS_SPI_FC8_CLOCK_SOURCE 12000000UL
/* Definition of peripheral ID */
#define BLE_USART_FC7_PERIPHERAL ((USART_Type *)FLEXCOMM7)
/* Definition of the clock source frequency */
#define BLE_USART_FC7_CLOCK_SOURCE 12000000UL
/* BLE_USART_FC7 interrupt vector ID (number). */
#define BLE_USART_FC7_FLEXCOMM_IRQN FLEXCOMM7_IRQn
/* BLE_USART_FC7 interrupt vector priority. */
#define BLE_USART_FC7_FLEXCOMM_IRQ_PRIORITY 3
/* BLE_USART_FC7 interrupt handler identifier. */
#define BLE_USART_FC7_FLEXCOMM_IRQHANDLER FLEXCOMM7_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const i2c_master_config_t OLED_I2C_FC1_config;
extern const spi_master_config_t VALVES_SPI_FC3_config;
extern const spi_master_config_t NEOPIXELS_SPI_FC8_config;
extern const usart_config_t BLE_USART_FC7_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals_cm33_core0(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
